# Generated by Django 5.0.3 on 2024-03-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='avg_rate',
            field=models.CharField(choices=[('1', 'fine'), ('2', 'good'), ('3', 'verygood'), ('4', 'excilent'), ('5', 'Top')], max_length=10),
        ),
    ]
