# Generated by Django 5.0.3 on 2024-03-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
        ('users', '0002_alter_customuser_email_alter_nurse_avg_rate'),
    ]

    operations = [
    ]
