# Generated by Django 5.0.3 on 2024-03-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20240317_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='specialty',
            field=models.CharField(blank=True, choices=[('1', 'قسم تمريض الباطني والجراحي'), ('2', 'قسم تمريض العناية الحرجة والطوارئ'), ('3', 'قسم تمريض النسا والتوليد'), ('4', 'قسم تمريض الأطفال'), ('5', 'قسم التمريض النفسي والصحة العقلية'), ('6', 'قسم إدارة التمريض'), ('7', 'قسم تمريض المسنين'), ('8', 'قسم تمريض صحة المجتمع')], max_length=50, null=True),
        ),
    ]
